-- Tabla de catálogo de productos (Tienda y Regaleria), para que el
-- catálogo se pueda administrar desde el panel admin en vez de estar
-- "hardcodeado" en el código de tienda.html / regaleria.html.
--
-- Correr este script UNA VEZ en Supabase → SQL Editor → Run.
-- Es seguro de volver a correr: usa "if not exists" y upserts por nombre.

create table if not exists productos_catalogo (
  id bigint generated by default as identity primary key,
  negocio text not null check (negocio in ('tienda','regaleria')),
  nombre text not null,
  categoria text not null,
  descripcion text,
  foto text,
  precio numeric,       -- precio unitario simple (Regaleria)
  tiers jsonb,           -- packs con descuento [{"qty":1,"precio":...}, ...] (Tienda)
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

alter table productos_catalogo enable row level security;

-- Cualquiera puede leer el catálogo (lo necesitan tienda.html y
-- regaleria.html, que no requieren login).
drop policy if exists "Lectura publica de productos" on productos_catalogo;
create policy "Lectura publica de productos"
  on productos_catalogo for select
  using (true);

-- Solo un usuario logueado (el admin) puede agregar, editar o borrar
-- productos.
drop policy if exists "Admin puede escribir productos" on productos_catalogo;
create policy "Admin puede escribir productos"
  on productos_catalogo for all
  to authenticated
  using (true)
  with check (true);

-- Permite que el admin (usuario logueado) suba, reemplace o borre fotos
-- en el bucket "productos-distribuidora" desde el panel. El bucket ya es
-- público para lectura; esto solo habilita la escritura para el admin.
drop policy if exists "Admin puede subir fotos de productos" on storage.objects;
create policy "Admin puede subir fotos de productos"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'productos-distribuidora');

drop policy if exists "Admin puede actualizar fotos de productos" on storage.objects;
create policy "Admin puede actualizar fotos de productos"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'productos-distribuidora');

drop policy if exists "Admin puede borrar fotos de productos" on storage.objects;
create policy "Admin puede borrar fotos de productos"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'productos-distribuidora');

-- Carga inicial: el catálogo que ya existía escrito en el código, para no
-- perder nada en la migración. Si ya corriste este script antes, no
-- duplica (solo inserta si la tabla está vacía).
insert into productos_catalogo (negocio,nombre,categoria,foto,tiers,precio)
select * from (values
  ('tienda','Hamburguesa Clásica x4','Hamburguesas','clasica-x4.jpg','[{"qty":1,"precio":4200},{"qty":3,"precio":11970},{"qty":5,"precio":18480}]'::jsonb,null::numeric),
  ('tienda','Hamburguesa Semillas x4','Hamburguesas','semillas-x4.jpg','[{"qty":1,"precio":4500},{"qty":3,"precio":12825},{"qty":5,"precio":19800}]'::jsonb,null),
  ('tienda','Hamburguesa Queso x4','Hamburguesas','queso-x4.jpg','[{"qty":1,"precio":4900},{"qty":3,"precio":13965},{"qty":5,"precio":21560}]'::jsonb,null),
  ('tienda','Hamburguesa Vegana x4','Hamburguesas','vegano-x4.jpg','[{"qty":1,"precio":4600},{"qty":3,"precio":13110},{"qty":5,"precio":20240}]'::jsonb,null),
  ('tienda','Hamburguesa Smash x4','Hamburguesas','smash-x4.jpg','[{"qty":1,"precio":3300},{"qty":3,"precio":9405},{"qty":5,"precio":14520}]'::jsonb,null),
  ('tienda','Pancho Corto Clásico x6','Panchos','corto-clasico-x6.jpg','[{"qty":1,"precio":3400},{"qty":3,"precio":9690},{"qty":5,"precio":14960}]'::jsonb,null),
  ('tienda','Pancho Corto Semillas x6','Panchos','corto-semillas-x6.jpg','[{"qty":1,"precio":3400},{"qty":3,"precio":9690},{"qty":5,"precio":14960}]'::jsonb,null),
  ('tienda','Pancho Corto Queso x6','Panchos','corto-queso-x6.jpg','[{"qty":1,"precio":4400},{"qty":3,"precio":12540},{"qty":5,"precio":19360}]'::jsonb,null),
  ('tienda','Pebete x2','Variedades','pebete-x2.jpg','[{"qty":1,"precio":1820},{"qty":3,"precio":5187},{"qty":5,"precio":8008}]'::jsonb,null),
  ('tienda','Pan de Molde x1','Variedades','molde-x1.jpg','[{"qty":1,"precio":3500},{"qty":3,"precio":9975},{"qty":5,"precio":15400}]'::jsonb,null),
  ('tienda','Árabe x4','Variedades','arabe-x4.jpg','[{"qty":1,"precio":2500},{"qty":3,"precio":7125},{"qty":5,"precio":11000}]'::jsonb,null),
  ('tienda','Lomitero x2','Variedades',null,'[{"qty":1,"precio":2600},{"qty":3,"precio":7410},{"qty":5,"precio":11440}]'::jsonb,null),
  ('tienda','Chips x6','Variedades','chips-comunes-x6.jpg','[{"qty":1,"precio":2250},{"qty":3,"precio":6412.50},{"qty":5,"precio":9900}]'::jsonb,null),
  ('tienda','Chips Queso x6','Variedades','chips-con-queso-x6.jpg','[{"qty":1,"precio":3100},{"qty":3,"precio":8835},{"qty":5,"precio":13640}]'::jsonb,null)
) as v(negocio,nombre,categoria,foto,tiers,precio)
where not exists (select 1 from productos_catalogo where negocio='tienda');

insert into productos_catalogo (negocio,nombre,categoria,foto,descripcion,precio)
select * from (values
  ('regaleria','Llavero en 3D Boca','Impresos 3D','llavero-3d-boca.jpg','Llavero impreso en 3D con el escudo de Boca Juniors, con brillo glitter.',2500::numeric),
  ('regaleria','Llavero 3D Feliz Día · Margarita','Impresos 3D','llavero-3d-feliz-dia-margarita.jpg','Llavero impreso en 3D con dije de margarita y cartel "Feliz Día".',2500),
  ('regaleria','Llavero 3D Feliz Día · Girasol','Impresos 3D','llavero-3d-feliz-dia-girasol.jpg','Llavero impreso en 3D con dije de girasol y cartel "Feliz Día".',2500),
  ('regaleria','Llavero 3D Feliz Día · Corazón','Impresos 3D','llavero-3d-feliz-dia-corazon.jpg','Llavero impreso en 3D con dije de corazón y cartel "Feliz Día".',2500),
  ('regaleria','Aerosol Saphirus Cony','Aromatizantes','saphirus-cony.jpg','Aromatizante de ambientes Saphirus, fragancia Cony. 185 g / 280 cc.',6800),
  ('regaleria','Textil Saphirus','Aromatizantes','textil-saphirus.jpg','Aromatizador textil Saphirus, 250 ml. Fragancias: Adventure, Pétalos de Orquídeas, Good Woman, Limón.',4000),
  ('regaleria','Velas de Noche Iluminarte x12 u.','Velas y Sahumerios','velas-noche-iluminarte-x12.jpg','Pack de 12 velas de noche Iluminarte Prestige, con vaso contenedor.',2600),
  ('regaleria','Sahumerios Alaukik Medianos','Velas y Sahumerios','sahumerios-alaukik-medianos.jpg','Sahumerios Alaukik Solitaire, varios aromas (Contra la Envidia, Archangels, Yoga Mantra, Orquídea, Kiwi, entre otros).',3200),
  ('regaleria','Souvenir Bautismo x1','Souvenirs/Candy Bar','souvenir-bautismo.jpg','Souvenir de bautismo impreso en 3D, ángel de la guarda con base, por unidad.',2000),
  ('regaleria','Souvenir Bautismo Personalizado x1','Souvenirs/Candy Bar','souvenir-bautismo-personalizado.jpg','Souvenir de bautismo impreso en 3D, angelito con base, personalizado con el nombre que elijas. Indicá el nombre en observaciones al hacer el pedido.',3500),
  ('regaleria','Taza Día de la Madre x1','Otros','tazas-dia-madre.jpg','Taza de vidrio con asa, diseño estampado alusivo al Día de la Madre. Varios diseños disponibles, por unidad.',4500),
  ('regaleria','Lapicero Personalizado','Artesanías','lapicero-personalizado.jpg','Lapicero de madera pintado, con espacio para lápices y block de notas, personalizado con el nombre que elijas. Indicá el nombre en observaciones al hacer el pedido.',8500)
) as v(negocio,nombre,categoria,foto,descripcion,precio)
where not exists (select 1 from productos_catalogo where negocio='regaleria');
